# Generated by Django 5.0.3 on 2024-04-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokerapp', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userrole',
            field=models.CharField(choices=[('normal', 'Normal'), ('superuser', 'Superuser')], default='normal', max_length=20),
        ),
    ]
